import java.lang.reflect.Array;
import java.sql.Date;

public class Operadores {
    public static void main(String[] args) {
        
        /*
         * + adição 
         * - subtração 
         * * multiplicação
         * / divisão 
         * % módulo 
         * = resultado 
         * 
         *  + strings faz a concatenação de strings 
         * ++         */

        /*
         * Operador Unário 
         */

        /*      == igual a 
                != diferenre de 
                > maior que
                >= maior ou igual
                < menor 
                <= menor ou igual 
         */ 

         /*
          * operadores lógicos 
            &&  -> &&
            ||  ou 
          */

    }
}
